ARG BASE
FROM ${BASE}

WORKDIR /app

COPY avenue /app/avenue
COPY ml-agents /app/ml-agents
RUN pip --no-cache-dir install Pillow \
  && pip --no-cache-dir install -e /app/ml-agents/ml-agents \
  && pip --no-cache-dir install -e /app/ml-agents/gym-unity \
	&& pip --no-cache-dir install -e /app/avenue

RUN mkdir /app/avenue_assets
ENV AVENUE_ASSETS /app/avenue_assets
COPY install.py /app/install.py

RUN python /app/install.py

RUN chmod 777 -R /app/avenue_assets