#!/usr/bin/env bash

# usage: ./build <image-name>


set -e  # exit on error
set -u  # raise error if variables undefined

IMAGE_NAME=${1-pytorch}
docker build -t $IMAGE_NAME .

echo "Successfully built $IMAGE_NAME"